# Monitor Rules
monitorrule=name:DP-1,width:3840,height:2160,refresh:240,x:0,y:10,scale:1,vrr:0,rr:0
#
#env=DISPLAY,:2
#monitorrule=name:eDP-1,width:2880,height:1801,refresh:60,x:0,y:0,scale:1.3,vrr:0,rr:0
#
exec-once=xwayland-satellite :2
